### ISSUE TITLE
Offline Install - Preflight check for seeded images

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#919] opened 2017-11-15 09:23 UTC
**FEATURE REQUEST**:

**What happened**:

When upgrading to the latest version of Kismatic for an offline install, Kismatic failed when trying to install the rescheduler as the new image was not in the private registry.

**What you would like to happen**:

It would be great if Kismatic could run a pre-flight check to make sure all required images have been seeded into the private registry before an offline installation or upgrade.

**Comment by alexbrand** [comment] 2017-11-15 12:10
Thanks! This is actually a duplicate of #810.

**Closed by alexbrand** 2017-11-15 12:10 UTC
