### ISSUE TITLE
Invalid numbering of smoke tests

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#181] opened 2016-12-20 17:10 UTC
```
Running Smoke Test==================================================================
1/3....  Configure Cluster Prerequisites                                        [OK]
2/3....  Update Hosts File                                                             [OK]
3/3....  Smoke test Master Nodes                                                [OK]
4/3....  Smoke test Master Nodes                                                [OK]
```

**Comment by alexbrand** [comment] 2016-12-20 18:17
Thanks @swade1987. This is a duplicate of https://github.com/apprenda/kismatic/issues/67

**Closed by alexbrand** 2016-12-20 18:17 UTC
