### ISSUE TITLE
Removing a PV created by Kismatic does not allow you to re-create it

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#769] opened 2017-09-04 10:36 UTC
**BUG REPORT**:

**What happened**:

Added a PV to a cluster via Kismatic:

```./kismatic volume add 12 elasticsearch -r 1 -d 1 -c="kismatic"```

Then removed the created volume via kubectl:

```kubectl delete pv elasticsearch```

When attempting to re-add the PV but without the storage class flag:

```./kismatic volume add 12 elasticsearch -r 1 -d 1```

Received this error:

```
Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                               [OK]
Validating SSH connectivity to nodes                                            [OK]

Add Persistent Storage Volume=======================================================
Add Gluster Volume                                                              [ERROR]
- Task: verify volume name is unique
  storage1:                                                                     [ERROR]
---- STDOUT ----
elasticsearch
---------------
error adding new volume: error running playbook: error running ansible: exit status 2
```

Running a `./kismatic volume list` shows:

```
Name:           elasticsearch
StorageClass:
Capacity:       12.00GB
Available:      12.00GB
Replica:        1
Distribution:   1
Bricks:         storage1:/data/elasticsearch
Status:         Unknown
Claim:
Pods:
```

**What you expected to happen**:

I expected the PV to be re-created as it no longer existed within Kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

See steps above.

**Anything else we need to know?**:

N/A

**Environment**:
- Two storage nodes in my cluster (storage1 and storage2)
- Kismatic version (use `kismatic version`): 1.5.3
- Plan file Gist (remove sensitive information if any): N/A
- Cloud provider or hardware configuration: Digital Ocean
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
```
- Kernel (e.g. `uname -a`): 
```
Linux bootstrap 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by willvrny** [comment] 2017-09-04 10:42
Here is the output of ansible.log:

https://gist.github.com/willvrny/b99fc4231eafa4ffc9b012cfa2d0b345

**Comment by willvrny** [comment] 2017-09-04 10:58
After further inspection I can see that Kismatic is deferring to Gluster for the validation check:

https://github.com/apprenda/kismatic/blob/4969c60e3e867e2ceafc0f42430155215978bc85/ansible/roles/volume-add/tasks/main.yaml

After ssh-ing onto the storage node: `./kismatic ssh storage1`

And running: `gluster volume list` it is returning:
```
elasticsearch
```
As a workaround I have run to remove the volume on one of the storage nodes: 
```
gluster volume stop elasticsearch
gluster volume delete elasticsearch
```

**Comment by swade1987** [comment] 2017-09-04 12:22
@alexbrand @dkoshkin note the above fixed the issue and we were able to re-create the PV again.

If we have `kismatic volume add` we really need to allow `kismatic volume delete`

**Comment by alexbrand** [comment] 2017-09-07 14:34
Thanks @swade1987 @willvrny 

Closing this as a duplicate of #542

**Closed by alexbrand** 2017-09-07 14:34 UTC
