### ISSUE TITLE
Adding useful Ops labels to nodes

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#112] opened 2016-11-23 14:55 UTC
I feel it would be useful to automate the nodes with labels such as "memory" and "cpu_cores"

**Comment by dasmb** [comment] 2016-11-30 03:17
Why would this be useful for a label? Should rounding be applied?

**Comment by josephjacks** [comment] 2016-11-30 15:55
@dasmb @swade1987 This seems like a duplicate of #133. Let's move discussion there. Closing this issue.

**Closed** 2016-11-30 15:55 UTC
