### ISSUE TITLE
UI not reachable after cluster setup

### ISSUE THREAD

**Issue by vishal-biyani** [apprenda/kismatic#155] opened 2016-12-08 14:51 UTC
I set up the Kubernetes with a 3 node setup (1 for etcd, 1 for master & 1 for worker) on Google cloud. The setup completes succssfully, I can access API and Kubectl commands work normally but UI does not load. It throws an error in browser:
```
Error: 'dial tcp 172.16.171.1:9090: i/o timeout'
Trying to reach: 'http://172.16.171.1:9090/'
```
The IP is from POD CIDR block range (pod_cidr_block: 172.16.0.0/16)

**Comment by dkoshkin** [comment] 2016-12-08 22:38
What is the pod status when running `kubectl describe pods --namesapce=kube-system`?
Are you able to curl the Dashboard service or pod url and port from one of the machines in the cluster?

**Comment by vishal-biyani** [comment] 2016-12-09 04:23
When I do curl from one of cluster nodes for UI URL, I get:

```
curl: (6) Could not resolve host: BuKduCeZzolonr524
<a href="/ui/">Moved Permanently</a>.
```
Output of command describe pods in kube-system namespace below:

```
Name:		kube-dns-v18-d9x8c
Namespace:	kube-system
Node:		ks-3/10.138.0.10
Start Time:	Thu, 08 Dec 2016 19:16:14 +0530
Labels:		k8s-app=kube-dns
		kubernetes.io/cluster-service=true
		version=v18
Status:		Running
IP:		172.16.171.0
Controllers:	ReplicationController/kube-dns-v18
Containers:
  kubedns:
    Container ID:	docker://22dc624ae508c62e0d6e2c4371b3944778bffc1d9d9f78665daecb90da0b8445
    Image:		gcr.io/google_containers/kubedns-amd64:1.8
    Image ID:		docker://sha256:597a45ef55ec52401fdcd2e1d6ee53c74b04afb264490d7fa67b6d98ad330dfe
    Ports:		10053/UDP, 10053/TCP
    Args:
      --domain=cluster.local
      --dns-port=10053
      --kubecfg-file=/var/lib/kubelet/kubeconfig
    Limits:
      cpu:	100m
      memory:	200Mi
    Requests:
      cpu:		100m
      memory:		100Mi
    State:		Running
      Started:		Thu, 08 Dec 2016 19:16:19 +0530
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:8080/healthz delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:		http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /etc/kubernetes/ca.pem from ssl-certs (rw)
      /var/lib/kubelet/kubeconfig from worker-kubeconfig (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nvq0k (ro)
    Environment Variables:	<none>
  dnsmasq:
    Container ID:	docker://37234fe88da7ab53f5729b02a160571af9df52d1af07c862246d26ef7016df40
    Image:		gcr.io/google_containers/kube-dnsmasq-amd64:1.4
    Image ID:		docker://sha256:3ec65756a89b70b4095e43a340a6e2d5696cac7a93a29619ff5c4b6be9af2773
    Ports:		53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
    State:		Running
      Started:		Thu, 08 Dec 2016 19:16:20 +0530
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nvq0k (ro)
    Environment Variables:	<none>
  healthz:
    Container ID:	docker://f3d09595b60bf37691e641de227a7f413020d6e0fa268d64eddfcd898c129a25
    Image:		gcr.io/google_containers/exechealthz-amd64:1.2
    Image ID:		docker://sha256:93a43bfb39bfe9795e76ccd75d7a0e6d40e2ae8563456a2a77c1b4cfc3bbd967
    Port:		8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null && nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      -port=8080
      -quiet
    Limits:
      cpu:	10m
      memory:	20Mi
    Requests:
      cpu:		10m
      memory:		20Mi
    State:		Running
      Started:		Thu, 08 Dec 2016 19:16:22 +0530
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nvq0k (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  worker-kubeconfig:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/kubelet/kubeconfig
  ssl-certs:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/kubernetes/ca.pem
  default-token-nvq0k:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-nvq0k
QoS Class:	Burstable
Tolerations:	<none>
No events.

Name:		kubernetes-dashboard-1872324879-iiydn
Namespace:	kube-system
Node:		ks-3/10.138.0.10
Start Time:	Thu, 08 Dec 2016 19:17:22 +0530
Labels:		app=kubernetes-dashboard
		pod-template-hash=1872324879
Status:		Running
IP:		172.16.171.1
Controllers:	ReplicaSet/kubernetes-dashboard-1872324879
Containers:
  kubernetes-dashboard:
    Container ID:	docker://c694361cf0d74e5887372c7ec73e2c137006352292ad862997e58fed57d53951
    Image:		gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.2
    Image ID:		docker://sha256:c0e4ba8968ee756368cbe5f64f39b0ef8e128de90d0bdfe1d040f0773055e68a
    Port:		9090/TCP
    State:		Running
      Started:		Thu, 08 Dec 2016 19:17:28 +0530
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nvq0k (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-nvq0k:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-nvq0k
QoS Class:	BestEffort
Tolerations:	<none>
```

**Comment by dkoshkin** [comment] 2016-12-09 14:08
Looks like the pod is running and`Could not resolve host: BuKduCeZzolonr524` seems wrong. 
Can you also try doing `curl http://172.16.171.1:9090/` from one the nodes to see if you can reach it directly.

**Comment by vishal-biyani** [comment] 2016-12-12 11:41
From the node on which the dashboard container is running, the curl gives an browser error. But I suspect if a better browser is used, this will lead to same error that I am getting
```
<!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title>Kubernetes Dashboard</title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.36bb79bb.css"> <link rel="stylesheet" href="static/app.347a608f.css"> </head> <body> <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
    <![endif]--> <kd-chrome layout="column" layout-fill> </kd-chrome> <script src="static/vendor.633c6c7a.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.0c465e49.js"></script> </body> </html>
```
I suspected that my ```load_balanced_fqdn``` was incorrect (it was not using master's IP) so I destroyed my cluster. While creating a new cluster with only pulic IPs:
```
  ks-1                                                                          [ERROR]
---- STDOUT ----
cluster may be unhealthy: failed to list members
---- STDERR ----
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
---------------
error installing: error running playbook: error running ansible: exit status 2
```
I get error around etcd_k8s.service and log from service are:

```
Dec 12 11:40:43 ks-1 etcd[5282]: recognized environment variable ETCD_NAME, but unused: shadowed by correspondi
Dec 12 11:40:43 ks-1 etcd[5282]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresp
Dec 12 11:40:43 ks-1 etcd[5282]: unrecognized environment variable ETCD_CLUSTER_TOKEN=etcd-cluster-k8s
Dec 12 11:40:43 ks-1 etcd[5282]: etcd Version: 3.0.13
Dec 12 11:40:43 ks-1 etcd[5282]: Git SHA: c99d0d4
Dec 12 11:40:43 ks-1 etcd[5282]: Go Version: go1.6.3
Dec 12 11:40:43 ks-1 etcd[5282]: Go OS/Arch: linux/amd64
Dec 12 11:40:43 ks-1 etcd[5282]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 12 11:40:43 ks-1 etcd[5282]: peerTLS: cert = /etc/etcd_k8s/etcd.pem, key = /etc/etcd_k8s/etcd-key.pem, ca =
Dec 12 11:40:43 ks-1 etcd[5282]: listen tcp 104.198.101.220:2380: bind: cannot assign requested address
Dec 12 11:40:43 ks-1 systemd[1]: etcd_k8s.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 11:40:43 ks-1 systemd[1]: Failed to start etcd key-value store.
-- Subject: Unit etcd_k8s.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd_k8s.service has failed.
-- 
-- The result is failed.
Dec 12 11:40:43 ks-1 systemd[1]: etcd_k8s.service: Unit entered failed state.
```

**Comment by dkoshkin** [comment] 2016-12-12 14:23
We haven't seen this error before,  can you try using the public interface for `ip` field (this is used for the setup) and the private interface for `internalip`, `load_balanced_fqdn` as the public IP of the master node.

**Comment by vishal-biyani** [comment] 2016-12-12 17:06
@dkoshkin Yes I am using public IP as ip and, private ip in internalup and load_balanced_fqdn as public of master. Still same error

**Comment by WillPlatnick** [comment] 2016-12-14 11:22
I ran into a similar issue with etcd. The problem was DNS, my servers weren't able to resolve the DNS names. When that happens etcd has issues starting/stopping cleanly and you'll run into binding issues. Try using the hosts file option and see if you have better luck.

**Comment by dkoshkin** [comment] 2016-12-14 13:00
Thanks @WillPlatnick that could be it, try either using resolvable hostnames in your plan file or use the `update_hosts_files=true`.

**Comment by pennpeng** [comment] 2016-12-15 01:01
i meet the same problem，just restart  the calico  container，and the same in monitor（grafana），is it a bug？？？

**Comment by dkoshkin** [comment] 2016-12-21 19:30
@vishal-biyani if you are still experiencing this issue, it is most likely caused by the GCE firewall rules around IP in IP encapsulation.

If you are using `networking: type: overlay` doing something like `gcloud compute firewall-rules create calico-ipip --allow 4 --network "default" --source-ranges "10.128.0.0/9"` will create the correct rules.

**Comment by vishal-biyani** [comment] 2016-12-26 12:12
@dkoshkin Thanks for suggestion. I tried it but ran into the same error. The Source-range you mentioned, is it dependent on pod_cidr_block or service_cidr_block?

```
3/17...  Update Hosts File                                                      [OK]
4/17...  Install Kubernetes Etcd Cluster                                        
- Running task: etcd : restart etcd service
  ks-1 Job for etcd_k8s.service failed because the control process exited with error code. See "systemctl status etcd_k8s.service" and "journalctl -xe" for details.
```

**Comment by alexbrand** [comment] 2016-12-26 12:45
@vishal-biyani I suspect this is a different issue. Are you still getting this issue?

```
Dec 12 11:40:43 ks-1 etcd[5282]: listen tcp 104.198.101.220:2380: bind: cannot assign requested address
```

Is that IP address assigned to any of the interfaces on the machine? It seems like etcd is unable to bind to that address.

**Comment by vishal-biyani** [comment] 2016-12-26 13:15
@alexbrand It is actually the same error in etcd service logs. I am not using ```internalip``` at all, would that be an issue specially in Gcloud environment?

```
Dec 26 13:14:08 ks-1 etcd[5458]: peerTLS: cert = /etc/etcd_k8s/etcd.pem, key = /etc/etcd_k8s/etcd-key.pem, ca = , trusted-ca =
Dec 26 13:14:08 ks-1 etcd[5458]: listen tcp 104.198.5.34:2380: bind: cannot assign requested address
Dec 26 13:14:08 ks-1 systemd[1]: etcd_k8s.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 13:14:08 ks-1 systemd[1]: Failed to start etcd key-value store.
```

**Comment by alexbrand** [comment] 2017-01-20 14:52
@vishal-biyani Did you end up figuring this out? I remember chatting about it on Slack.

**Comment by vishal-biyani** [comment] 2017-02-01 04:33
@alexbrand I was a bit busy and sorry but could not try it out. Will give it a shot next week first thing.

**Comment by alexbrand** [comment] 2017-02-01 13:00
@vishal-biyani No worries at all! I was mainly wondering if we could help with anything. Let us know!

**Comment by alexbrand** [comment] 2017-02-11 13:26
@vishal-biyani  Feel free to reopen if you run into issues

**Closed by alexbrand** 2017-02-11 13:26 UTC
Labels: troubleshooting

**Comment by snyamars** [comment] 2017-08-03 05:35
Hi, I am using kismatic 1.4.1 version. Trying to set up a kubernetes cluster of 1-1-1 on AWS.
I am getting exactly the same error. Tried the above suggested options and getting exactly the same errors.
Any suggestions how I can access UI from the cluster?

**Comment by alexbrand** [comment] 2017-08-03 10:45
Hey @snyamars! There are various errors in this issue. Can you be more specific as to what exactly you are running into?

**Comment by snyamars** [comment] 2017-08-03 12:58
Hi @alexbrand, I tried to setup kubernetes cluster with 1 master, 1 etcd and 1 worker on AWS.
The cluster installation completes successfully. But smoke test never completes (kuberang timesout after a long time). Unable to access dashboard though the pods are running including the dashboard pod.

**Comment by alexbrand** [comment] 2017-08-03 12:59
Hmm. Sounds like a networking issue. Can you share your plan file to get an idea of your environment? Thanks

**Comment by snyamars** [comment] 2017-08-03 13:06
[kismatic-cluster_1.txt](https://github.com/apprenda/kismatic/files/1197256/kismatic-cluster_1.txt)

**Comment by alexbrand** [comment] 2017-08-03 13:09
Thanks! Can you also share or detail the security groups you have setup in your AWS environment?

**Comment by snyamars** [comment] 2017-08-03 13:15
Default subnet group, ICMP ports enabled for ping between all nodes in cluster
relevant ports like 6443, 10250 -10350, 2380, 8443, 9090, 6660 ports are enabled.

**Comment by alexbrand** [comment] 2017-08-03 13:21
Thanks. Inter-node connectivity must be allowed on all ports. Seems like this is not the case?

**Comment by snyamars** [comment] 2017-08-03 13:26
Is there any specific action to be done to enable inter-node connectivity?

**Comment by snyamars** [comment] 2017-08-03 13:30
All nodes are part of the same VPC subnet. Is it not sufficient for inter node communication?

**Comment by alexbrand** [comment] 2017-08-03 13:34
The security groups must allow communication between them. I have found this documentation helpful in the past: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html#DefaultSecurityGroup

**Comment by snyamars** [comment] 2017-08-03 13:37
Thanks @alexbrand. I am following the same documentation. Let me verify again and re-run the installation. Keep you posted.
